name: Docker image vulnerability scan workflow

on: [push, workflow_dispatch]

jobs:
    meterian_container_scan:
        name: Meterian container scan
        runs-on: ubuntu-latest

        steps:
          - name: Checkout (official GitHub action)
            uses: actions/checkout@v3

          - name: Install Meterian Docker scanner
            run: |
                wget -q -O docker-scan.sh https://raw.githubusercontent.com/MeterianHQ/docker-scanner-engine/master/docker-scan-ci.sh
                chmod +x docker-scan.sh

          - name: Prep image to scan
            run: |            
                docker pull redis:latest
                mkdir reports

          - name: Perform scan
            run: ./docker-scan.sh redis:latest --report-console --report-pdf=reports/report.pdf --report-json=reports/report.json
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }} 
          
          - uses: actions/upload-artifact@v3
            with:
              name: meterian-reports
              path: reports
